In [1]:
import os
import pandas as pd
import numpy as np
os.chdir('..')
os.chdir('..')


In [2]:
pwd

'/home/ayush/Ayush/Internship/Medical'

In [3]:
abp= np.load('data/data/N/test_abp1.npy')

In [4]:
abp

array([[ 78.46785814, 109.36194947,  56.90338148],
       [ 75.20546272, 106.96858836,  56.31725223],
       [ 79.01842888, 108.67813201,  59.98056005],
       ...,
       [ 77.46245109, 105.69864165,  60.46900109],
       [ 74.15550986, 103.94025389,  57.92910767],
       [ 73.51193994, 105.11251239,  57.97795177]])

In [5]:
abp.shape

(5544, 3)

In [6]:
ecg= np.load('data/data/N/test_ecg1.npy')

In [7]:
ecg

array([[ 0.04003906,  0.05517578,  0.06005859, ...,  0.01025391,
        -0.02978516, -0.06494141],
       [-0.08984375, -0.09472656, -0.09472656, ..., -0.08007812,
        -0.08496094, -0.08984375],
       [-0.08496094,  0.        ,  0.22509766, ...,  0.22509766,
         0.45507812,  0.49511719],
       ...,
       [ 0.25      ,  0.24511719,  0.24511719, ...,  0.30029297,
         0.31005859,  0.31494141],
       [ 0.30029297,  0.28515625,  0.26025391, ...,  0.18994141,
         0.18994141,  0.18994141],
       [ 0.18994141,  0.1953125 ,  0.18994141, ...,  0.14501953,
         0.14013672,  0.13525391]])

In [8]:
ecg.shape

(5544, 125)

In [9]:
ppg= np.load('data/data/N/test_ppg1.npy')

In [10]:
ppg

array([[1.8797654 , 1.84946237, 1.81622678, ..., 1.74193548, 1.70185728,
        1.65982405],
       [1.61388074, 1.5659824 , 1.51612903, ..., 1.47018573, 1.43010753,
        1.38807429],
       [1.34213099, 1.29423265, 1.24731183, ..., 1.6686217 , 1.62463343,
        1.58651026],
       ...,
       [1.07820137, 1.08602151, 1.10948192, ..., 2.89931574, 2.93352884,
        2.95307918],
       [2.96285435, 2.971652  , 2.97360704, ..., 2.09677419, 2.07038123,
        2.04692082],
       [2.02541544, 2.00097752, 1.97653959, ..., 1.43890518, 1.42326491,
        1.41055718]])

In [11]:
ppg.shape

(5544, 125)

In [12]:
# # import numpy as np

# # Load the three .npy files
# # file1 = np.load('file1.npy')
# # file2 = np.load('file2.npy')
# # file3 = np.load('file3.npy')

# # Concatenate the rows
# concatenated_array = np.hstack((abp, ecg, ppg))

# # Create a column with the target value 0
# target_column = np.zeros((concatenated_array.shape[0], 1))

# # Add the target column to the concatenated array
# concatenated_array_with_target = np.hstack((concatenated_array, target_column))

# # Print the shape of the new array to verify
# print(concatenated_array_with_target.shape)

# # Save the new array if needed
# # np.save('concatenated_array_with_target.npy', concatenated_array_with_target)


In [13]:
# concatenated_array_with_target

In [14]:
def col_concat(abp, ecg, ppg,con_arr):
    concatenated_array = np.hstack((abp, ecg, ppg))
    target_column = np.zeros((concatenated_array.shape[0], 1))
    concatenated_array_with_target = np.hstack((concatenated_array, target_column))
    concatenated_array_with_target= np.vstack((con_arr, concatenated_array_with_target))
    return concatenated_array_with_target

In [15]:
concatenated_array_with_target=np.empty((0,254))
concatenated_array_with_target=col_concat(abp, ecg, ppg, concatenated_array_with_target)
concatenated_array_with_target.shape

(5544, 254)

In [16]:
# Loop to generate filenames and read each file
for i in range(1, 11):
    filename = f'test_abp{i}.npy'
    abp = np.load(f'data/data/N/{filename}')
    filename = f'test_ecg{i}.npy'
    ecg = np.load(f'data/data/N/{filename}')
    filename = f'test_ppg{i}.npy'
    ppg = np.load(f'data/data/N/{filename}')
    concatenated_array_with_target=col_concat(abp, ecg, ppg, concatenated_array_with_target)

concatenated_array_with_target.shape


(61528, 254)

In [17]:
concatenated_array_with_target

array([[ 78.46785814, 109.36194947,  56.90338148, ...,   1.70185728,
          1.65982405,   0.        ],
       [ 75.20546272, 106.96858836,  56.31725223, ...,   1.43010753,
          1.38807429,   0.        ],
       [ 79.01842888, 108.67813201,  59.98056005, ...,   1.62463343,
          1.58651026,   0.        ],
       ...,
       [ 69.68217141,  94.41565356,  57.58719894, ...,   2.80840665,
          2.76539589,   0.        ],
       [ 66.93830501,  93.53645968,  57.44066662, ...,   1.37634409,
          1.40860215,   0.        ],
       [ 72.94495758,  95.29484744,  58.02679588, ...,   1.17497556,
          1.1886608 ,   0.        ]])